In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 10])

In [3]:
a.shape

(8,)

In [4]:
a.ndim

1

In [5]:
a.size

8

In [9]:
b = np.array([[2, 3, 4, 5,  6,  7],
              [3, 6, 7, 8, 10, 11]])

In [11]:
b.ndim

2

In [12]:
b.size

12

In [13]:
b.shape

(2, 6)

In [18]:
c = np.array([[[1, 2, 3],
               [3, 4, 5],
               [7, 8, 11] ],
             [[1, 2, 3],
               [3, 4, 5],
               [7, 8, 11] ],
             [[1, 2, 3],
               [3, 4, 5],
               [7, 8, 11] ],])

In [19]:
c.size


27

In [20]:
c.shape

(3, 3, 3)

In [17]:
c.ndim

3

In [22]:
a

array([ 1,  2,  3,  4,  5,  6,  7, 10])

In [21]:
a[2:]

array([ 3,  4,  5,  6,  7, 10])

In [24]:
a[0:2]

array([1, 2])