#### Imporatre tutte le librerie che servono per la previsione i.e : tensorflow, pillow: PIL, numpy

In [1]:
import os
import tensorflow.keras
from PIL import Image, ImageOps
import numpy as np

#### Caricare il modello (rete neurale in tensorflow) che abbiamo allenato in TM.

In [3]:
# Disable scientific notation for clarity
np.set_printoptions(suppress=True)

# Load the model
model = tensorflow.keras.models.load_model('modello/keras_model.h5')

#### Uso la libreria os per accedere in maniera sequanziale alle immagini

In [5]:
cartella = "C:/Users/alket/datascience_2605/dati/testmask/testmask/"

In [6]:
lista_file = os.listdir(cartella)

In [9]:
for i in lista_file: 
    print('C:/Users/alket/datascience_2605/dati/testmask/testmask/'+str(i))
    data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

    # Replace this with the path to your image
    image = Image.open('C:/Users/alket/datascience_2605/dati/testmask/testmask/'+str(i))
    #resize the image to a 224x224 with the same strategy as in TM2:
    #resizing the image to be at least 224x224 and then cropping from the center
    size = (224, 224)
    image = ImageOps.fit(image, size, Image.ANTIALIAS)

    #turn the image into a numpy array
    image_array = np.asarray(image)

    # display the resized image
    # image.show()

    # Normalize the image
    normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1

    # Load the image into the array
    data[0] = normalized_image_array
    
    # run the inference
    prediction = model.predict(data)
    print(i)
    print(prediction)

    #0 Mask
    #1 NoMask
    #  Mask       NoMask

C:/Users/alket/datascience_2605/dati/testmask/testmask/mask1.jpg
mask1.jpg
[[0.9999963  0.00000366]]
C:/Users/alket/datascience_2605/dati/testmask/testmask/mask10.jpg
mask10.jpg
[[0.9999223  0.00007772]]
C:/Users/alket/datascience_2605/dati/testmask/testmask/mask2.jpg
mask2.jpg
[[0.9999902  0.00000981]]
C:/Users/alket/datascience_2605/dati/testmask/testmask/mask3.jpg
mask3.jpg
[[0.9999895  0.00001054]]
C:/Users/alket/datascience_2605/dati/testmask/testmask/mask4.jpg
mask4.jpg
[[0.99928916 0.00071084]]
C:/Users/alket/datascience_2605/dati/testmask/testmask/mask5.jpg
mask5.jpg
[[0.99929166 0.00070837]]
C:/Users/alket/datascience_2605/dati/testmask/testmask/mask6.jpg
mask6.jpg
[[0.9980611  0.00193884]]
C:/Users/alket/datascience_2605/dati/testmask/testmask/mask7.jpg
mask7.jpg
[[0.9999192  0.00008082]]
C:/Users/alket/datascience_2605/dati/testmask/testmask/mask8.jpg
mask8.jpg
[[0.9998723  0.00012761]]
C:/Users/alket/datascience_2605/dati/testmask/testmask/mask9.jpg
mask9.jpg
[[0.9999598  0