In [5]:
import numpy as np
import pandas as pd

##### Creare un array numpy

In [6]:
arr0 = np.array([1, 2, 3, 4, 9])

In [7]:
arr0

array([1, 2, 3, 4, 9])

In [8]:
dati = pd.DataFrame({"nome":["Marta", "Maria", "Mario"], "eta":[18, 19, 20]})

In [11]:
type(dati["eta"].values)

numpy.ndarray

##### Accedere agli elementi di un array

In [18]:
arr0[2:]

array([3, 4, 9])

In [22]:
arr1 = np.array([[1, 2, 3], 
                 [3, 4, 5], 
                 [4, 5, 6]])

In [23]:
arr1.shape

(3, 3)

In [24]:
arr1.ndim

2

In [32]:
arr3 = np.array([[[1, 2, 3],
                  [3, 4, 5],
                  [6, 8 ,9]],
                 [[10,20,3],
                  [1, 4, 5],
                  [6, 8 ,1]],
                 [[4, 2, 1],
                  [6, 4, 1],
                  [9, 8 ,1]]])

In [33]:
arr3.shape

(3, 3, 3)

In [34]:
arr3.size

27

In [35]:
arr4 = np.arange(16)

In [36]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
arr4.ndim

1

#### Reshape numpy array

In [42]:
arr4_re = arr4.reshape(8, 2)

In [43]:
arr4_re

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

##### Operazioni con gli array

In [53]:
arr_a = np.array([1, 2, 3, 4, 16])
arr_b = np.array([4, 5, 6, 7, 8])

In [54]:
somma_ab = arr_a + arr_b
somma_ab

array([ 5,  7,  9, 11, 24])

In [55]:
diff_ab = arr_a - arr_b
diff_ab

array([-3, -3, -3, -3,  8])

In [56]:
mol_ab = arr_a * arr_b
mol_ab

array([  4,  10,  18,  28, 128])

In [57]:
div_ab = arr_a / arr_b
div_ab

array([0.25      , 0.4       , 0.5       , 0.57142857, 2.        ])

In [58]:
div_ab = arr_a // arr_b
div_ab

array([0, 0, 0, 0, 2], dtype=int32)

In [59]:
arr_b

array([4, 5, 6, 7, 8])

In [62]:
magg6 = arr_b[arr_b > 6]

In [63]:
magg6

array([7, 8])

In [65]:
min5 = arr_b[arr_b < 5]

In [66]:
min5

array([4])

In [67]:
arr_b

array([4, 5, 6, 7, 8])

In [69]:
media = np.mean(arr_b)
media

6.0

In [71]:
mass = np.max(arr_b)
mass

8

In [72]:
min_e = np.min(arr_b)
min_e

4

In [73]:
np.square(arr_b)

array([16, 25, 36, 49, 64], dtype=int32)

##### Mettere insieme gli array con hstack e vstack

In [75]:
arr_c = np.array([[4, 5, 6, 7, 8], 
              [3, 4, 9, 9, 1]])
arr_d = np.array([[4, 5, 6, 7, 8], 
               [1, 2, 9, 0, 4]])

In [77]:
arr_tot_h = np.hstack( (arr_c, arr_d) )
arr_tot_h

array([[4, 5, 6, 7, 8, 4, 5, 6, 7, 8],
       [3, 4, 9, 9, 1, 1, 2, 9, 0, 4]])

In [78]:
arr_tot_v = np.vstack( (arr_c, arr_d) )
arr_tot_v

array([[4, 5, 6, 7, 8],
       [3, 4, 9, 9, 1],
       [4, 5, 6, 7, 8],
       [1, 2, 9, 0, 4]])

##### Salva una numpy array in un file

In [81]:
np.savetxt("arr_tot_v.csv", arr_tot_v)