### Example of how to use Cross validation on a classification problem

##### The points that this notebook covers are :

- 5-Fold validation 


- 10-Fold validation


-  Bias and variance


- Grid searching the best parameters of the model 

 

#### Load the dataset

In [62]:
from sklearn.datasets import load_iris

In [63]:
iris = load_iris()

In [64]:
X = iris.data
y = iris.target

In [65]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [66]:
type(y)

numpy.ndarray

#### Split the dataset into training set and testing set

In [11]:
from sklearn.model_selection import train_test_split

In [146]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=1)

In [147]:
X_test.shape

(30, 4)

### Classification algorithm KNN 

In [148]:
from sklearn.neighbors import KNeighborsClassifier

In [161]:
knn = KNeighborsClassifier(n_neighbors=35)

In [162]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=35)

In [163]:
previsione = knn.predict(X_test)

In [164]:
previsione

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2])

In [165]:
from sklearn import metrics

In [166]:
metrics.accuracy_score(previsione, y_test)

0.9666666666666667

1- is this result too good to be true ? 

2- was I simply lucky ? 

3- is the data somehow biased ? 

### Cross validation 5-Fold version

K = 5

In [115]:
from sklearn.model_selection import cross_val_score

In [116]:
k_fold = 5
score = cross_val_score(knn, X, y, cv = k_fold, scoring="accuracy")

In [28]:
score

array([0.9       , 0.96666667, 0.93333333, 0.9       , 1.        ])

In [30]:
bias = score.mean()
print(bias)

0.9399999999999998


In [31]:
variance = score.std()
print(variance)

0.038873012632301994


### Cross validation 10-Fold version

- K = 10

In [119]:
k_fold = 10
score = cross_val_score(knn, X, y, cv = k_fold, scoring="accuracy")

In [120]:
score

array([1.        , 0.93333333, 1.        , 0.93333333, 0.86666667,
       1.        , 0.93333333, 1.        , 1.        , 1.        ])

#### Compute and display bias and variance

In [37]:
bias = score.mean()
print(bias)

0.9533333333333334


In [38]:
variance = score.std()
print(variance)

0.04268749491621898


#### Use of GridSearchCV class for fine tuning the model 

In [167]:
from sklearn.model_selection import GridSearchCV

##### Define a range where to vary the parameters of the model

In [168]:
k_range = list(range(1, 31))

In [169]:
print(k_range)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


In [170]:
param_grid = dict(n_neighbors = k_range)

#### Declare the GridSearchCV instance and start using it with a given cross-validation parameter 

In [172]:
k_fold = 5
grid = GridSearchCV(knn, param_grid, cv = k_fold, scoring="accuracy")

In [173]:
grid

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=35),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                                         23, 24, 25, 26, 27, 28, 29, 30]},
             scoring='accuracy')

### Fit the GridSearchCV in order to find the best parameter/parameters 

In [174]:
grid.fit(X, y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=35),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                                         23, 24, 25, 26, 27, 28, 29, 30]},
             scoring='accuracy')

### Transform the results of GridSearchCV into a dataframe and sort by bias

In [175]:
import pandas as pd
data_grid = pd.DataFrame(grid.cv_results_)

In [176]:
data_grid

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000752,0.000283,0.002339,0.000851,1,{'n_neighbors': 1},0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,19
1,0.000659,0.000119,0.002612,0.000333,2,{'n_neighbors': 2},0.966667,0.933333,0.933333,0.900000,1.0,0.946667,0.033993,26
2,0.000570,0.000056,0.002210,0.000860,3,{'n_neighbors': 3},0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,10
3,0.000704,0.000214,0.002392,0.000818,4,{'n_neighbors': 4},0.966667,0.966667,0.966667,0.966667,1.0,0.973333,0.013333,6
4,0.000487,0.000055,0.001689,0.000242,5,{'n_neighbors': 5},0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,6
5,0.000523,0.000051,0.001817,0.000336,6,{'n_neighbors': 6},0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
6,0.000544,0.000068,0.001614,0.000115,7,{'n_neighbors': 7},0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
7,0.000484,0.000037,0.001680,0.000163,8,{'n_neighbors': 8},0.966667,1.000000,0.933333,0.933333,1.0,0.966667,0.029814,10
8,0.000559,0.000099,0.001739,0.000187,9,{'n_neighbors': 9},0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,6
9,0.000546,0.000064,0.001739,0.000220,10,{'n_neighbors': 10},0.966667,1.000000,1.000000,0.933333,1.0,0.980000,0.026667,1


### All what we need from the GridSearchCV results are these four fields i.e. 

- best parameter for the classification model


- the bias 


- the variance 


- the rank of the test score

In [177]:
dati_scoring = data_grid[["params", "mean_test_score", "std_test_score", "rank_test_score"]]

In [178]:
dati_scoring.sort_values("rank_test_score")

,params,mean_test_score,std_test_score,rank_test_score
10,{'n_neighbors': 11},0.980000,0.026667,1
5,{'n_neighbors': 6},0.980000,0.016330,1
6,{'n_neighbors': 7},0.980000,0.016330,1
9,{'n_neighbors': 10},0.980000,0.026667,1
11,{'n_neighbors': 12},0.980000,0.026667,1
3,{'n_neighbors': 4},0.973333,0.013333,6
4,{'n_neighbors': 5},0.973333,0.024944,6
8,{'n_neighbors': 9},0.973333,0.024944,6
12,{'n_neighbors': 13},0.973333,0.024944,6
18,{'n_neighbors': 19},0.966667,0.029814,10
